# language: python

# python:
#   - "3.9"

# install:
#   - pip install -r requirements.txt
  
#   - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  
#   - source ~/.nvm/nvm.sh  
#   - nvm install 16  
#   - node --version  

# before_script: 
#   - chmod +x script.sh

# jobs:
#   include:
#     - name: add and sub test
#       script: pytest  

#     - name: extract rNumber and store
#       script: node publish_release.js  

#     - name: making pull request
#       script: ./script.sh  



language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  # Install Node.js using NVM
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  
  - source ~/.nvm/nvm.sh  
  - nvm install 16  
  - node --version  

  # Install GitHub CLI (gh)
  - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /usr/share/keyrings/github.asc
  - sudo apt-key add /usr/share/keyrings/github.asc
  - sudo apt-add-repository https://cli.github.com/packages
  - sudo apt-get update
  - sudo apt-get install gh  # Install GitHub CLI

before_script:
  - chmod +x script.sh  # Ensure script.sh is executable

jobs:
  include:
    - name: add and sub test
      script: pytest

    # Step for extracting release number and storing it
    - name: extract rNumber and store
      script: node publish_release.js  # Run your Node.js script to create the releaseNumber.txt file

    # Step for making a pull request (call the script directly instead of from within itself)
    - name: making pull request
      script: ./script.sh
