language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt

  # Install Node.js using NVM
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  
  - source ~/.nvm/nvm.sh  
  - nvm install 16  
  - node --version  

  # Install GitHub CLI (gh) via the official GitHub CLI installation script
  - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
  - sudo snap install gh

before_script:
  - chmod +x script.sh  

  # DEBUG STEP
  - echo "Files in current directory:"  
  - ls -l 

  # Decode the SSH private key and add it to the SSH agent
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

  - ssh-keyscan github.com >> ~/.ssh/known_hosts  # To avoid "host verification" prompts
  - eval $(ssh-agent -s)  # Start the SSH agent
  - ssh-add ~/.ssh/id_rsa  # Add the SSH key to the agent

  - echo "Authenticating with GH_TOKEN"
  - export GH_TOKEN="$GH_TOKEN"

cache: 
  directories:
    - $(pwd)

jobs:
  include:
    - name: sub and add test
      script: pytest

    - name: generate releaseNumber.txt file
      script: |
        node publish_release.js  
        echo "Files in current directory: $(pwd)"
        ls -l
      workspaces:
        create:
          name: shared-workspace
          paths:
            - releaseNumber.txt

    - name: extract rNumber and store
      workspaces:
        use: shared-workspace
      script: |
        echo "Files in current directory: $(pwd)"
        ls -l
        ./script.sh
