language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  
  - source ~/.nvm/nvm.sh  
  - nvm install 16  
  - node --version  

before_script: 
  - chmod +x script.sh

jobs:
  include:
    # - name: add and sub test
    #   script: pytest  

    - name: extract rNumber and store
      script: node publish_release.js  

    - name: making pull request
      script: ./script.sh  