language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  # Install Node.js using NVM
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  
  - source ~/.nvm/nvm.sh  
  - nvm install 16  
  - node --version  

  # Install GitHub CLI (gh) via the official GitHub CLI installation script
  - curl -fsSL https://cli.github.com/install.sh | bash

before_script:
  - chmod +x script.sh  # Ensure script.sh is executable
  - echo "Files in current directory:"  # Debugging step
  - ls -l  # List files to ensure releaseNumber.txt exists

jobs:
  include:
    #running the python script
    - name: sub and add test
      script: pytest

    # Step for extracting release number and storing it
    - name: extract rNumber and store
      # script: node publish_release.js  # Run your Node.js script to create the releaseNumber.txt file
      script: |
        node publish_release.js  # Run your Node.js script to create the releaseNumber.txt file
        echo "Files in current directory:"
        ls -l   # List files in the directory to check if releaseNumber.txt exists


    # Step for making a pull request (call the script directly instead of from within itself)
    - name: making pull request
      script: ./script.sh
