language: python

python:
  - "3.9"  # Use a stable Python version like 3.9 or 3.8

install:
  - pip install -r requirements.txt  # Install dependencies from requirements.txt

script:
  - pytest  # Run the tests using pytest
