language: python

python:
  - "3.9"  

install:
  - pip install -r requirements.txt 
  - nvm install node
  - node --version
  - npm install

jobs:
  include:
    - name: add and sub test
    - script: pytest

    - name: extract rNumber and store
    - script: node publish_release.js

    - name: making pul request
    - script: script.sh